'use strict'

const ActionType = {
   UPDATE_CUSTOMER_LIST: 'UPDATE_CUSTOMER_LIST',
   UPDATE_ADPOSITION_LIST: 'UPDATE_ADPOSITION_LIST',
   UPDATE_RECHARGE_LIST: 'UPDATE_RECHARGE_LIST',
   UPDATE_ADDATE_LIST: 'UPDATE_ADDATE_LIST',
}

export default ActionType;
